// <auto-generated />
using BakeSale.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BakeSale.Migrations
{
    [DbContext(typeof(BakeSaleDbContext))]
    [Migration("20250611082654_SeedInitialItems")]
    partial class SeedInitialItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BakeSale.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsFixedStock")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsFixedStock = true,
                            Name = "Brownie",
                            Price = 0.65m,
                            Quantity = 48
                        },
                        new
                        {
                            Id = 2,
                            IsFixedStock = true,
                            Name = "Muffin",
                            Price = 1.00m,
                            Quantity = 36
                        },
                        new
                        {
                            Id = 3,
                            IsFixedStock = true,
                            Name = "Cake Pop",
                            Price = 1.35m,
                            Quantity = 24
                        },
                        new
                        {
                            Id = 4,
                            IsFixedStock = true,
                            Name = "Apple Tart",
                            Price = 1.50m,
                            Quantity = 60
                        },
                        new
                        {
                            Id = 5,
                            IsFixedStock = true,
                            Name = "Water",
                            Price = 1.50m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 6,
                            IsFixedStock = false,
                            Name = "Shirt",
                            Price = 2.00m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 7,
                            IsFixedStock = false,
                            Name = "Pants",
                            Price = 3.00m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 8,
                            IsFixedStock = false,
                            Name = "Jacket",
                            Price = 4.00m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 9,
                            IsFixedStock = false,
                            Name = "Toy",
                            Price = 1.00m,
                            Quantity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
